development:
  adapter: mysql2
  database: cubic_poo_development
  username: root
  password: password
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: cubic_poo_production
  username: root
  password: password
  encoding: utf8
